version: "3.8"

networks:
  netPRO390:
    external: false



services:

#Databases
#####################################################################################################

  UserAuthenticationDB:
    image: mysql:latest
    container_name: UserAuthenticationDB
    environment:
      MYSQL_ROOT_PASSWORD: test1234
      MYSQL_DATABASE: userdb
      MYSQL_USER: user
      MYSQL_PASSWORD: test1234
    ports:
      - "3306:3306"
    networks:
      - netPRO390
    volumes:
      - db_data:/var/lib/mysql
      - ./UserAuthSQL:/docker-entrypoint-initdb.d

  CarServiceDB:
    container_name: CarServiceDB
    image: mongo:latest
    restart: always
    hostname: CarServiceDB
    ports:
      - "27017:27017"
    networks:
      - netPRO390
    volumes:
      - mongo_data:/data/db

#Service Registery and API Gateway
#####################################################################################################

  EurekaServer:
    container_name: EurekaServer
    image: steeltoeoss/eureka-server:latest
    restart: always
    hostname: EurekaServer
    ports:
      - 8761:8761
    networks:
      - netPRO390

  CarManagerAPIGateway:
    container_name: CarManagerAPIGateway
    build:
      context: ./dotnet-apigateway-ocelot
      dockerfile: Dockerfile
    image: carmanagerocelotgatewayapi:1
    restart: always
    hostname: CarManagerAPIGateway
    ports:
      - 5041:80
    networks:
      - netPRO390

#API Services
#####################################################################################################

  UserAuthenticationServiceAPI:
    build:
      context: ./userauthenticationserviceapi
      dockerfile: Dockerfile
    image: userauthenticationserviceapi:1
    restart: always
    hostname: UserAuthenticationServiceAPI
    ports:
      - 3000:3000
    networks:
      - netPRO390
    depends_on:
      - EurekaServer
      - UserAuthenticationDB
      - CarManagerAPIGateway

#####################################################################################################

volumes:
  db_data:
  mongo_data:





