version: "3.8"

networks:
  netPRO390:
    external: false



services:

#Kafka
#####################################################################################################
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    volumes:
      - zookeeper-data:/var/lib/zookeeper
    networks:
      - netPRO390

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
    volumes:
      - kafka-data:/var/lib/kafka  
    networks:
      - netPRO390
    ports:
      - "9092:9092"    

#Databases
#####################################################################################################

  UserServiceDB:
    image: mysql:latest
    container_name: UserServiceDB
    environment:
      MYSQL_ROOT_PASSWORD: test1234
      MYSQL_DATABASE: userdb
      MYSQL_USER: user
      MYSQL_PASSWORD: test1234
    ports:
      - "3306:3306"
    networks:
      - netPRO390
    volumes:
      - db_data_users:/var/lib/mysql
      - ./Scripts/UserServiceSQL:/docker-entrypoint-initdb.d

  CarServiceDB:
    container_name: CarServiceDB
    image: mongo:latest
    restart: always
    hostname: CarServiceDB
    ports:
      - "27017:27017"
    networks:
      - netPRO390
    volumes:
      - mongo_data:/data/db

  MaintenanceReminderServiceDB:
    image: mysql:latest
    container_name: MaintenanceReminderServiceDB
    environment:
      MYSQL_ROOT_PASSWORD: test1234
      MYSQL_DATABASE: maintenancereminderdb
      MYSQL_USER: user
      MYSQL_PASSWORD: test1234
    ports:
      - "3307:3306"
    networks:
      - netPRO390
    volumes:
      - db_data_maintenancereminder:/var/lib/mysql
      - ./Scripts/MaintenanceReminderServiceSQL:/docker-entrypoint-initdb.d

  NotificationServiceDB:
    image: redis:latest
    container_name: NotificationServiceDB
    ports:
      - "6379:6379"
    networks:
      - netPRO390
    volumes:
      - redis_data:/data


#Service Registery and API Gateway
#####################################################################################################

  EurekaServer:
    container_name: EurekaServer
    image: steeltoeoss/eureka-server:latest
    restart: always
    hostname: EurekaServer
    ports:
      - 8761:8761
    networks:
      - netPRO390

  CarManagerAPIGateway:
    container_name: CarManagerAPIGateway
    build:
      context: ./dotnet-apigateway-ocelot
      dockerfile: Dockerfile
    image: carmanagerocelotgatewayapi:1
    restart: always
    hostname: CarManagerAPIGateway
    ports:
      - 5041:80
    networks:
      - netPRO390

#API Services
#####################################################################################################

  UserServiceAPI:
    build:
      context: ./userserviceapi
      dockerfile: Dockerfile
    image: userserviceapi:1
    restart: always
    hostname: UserServiceAPI
    ports:
      - 3000:3000
    networks:
      - netPRO390
    depends_on:
      - EurekaServer
      - UserServiceDB
      - CarManagerAPIGateway

  CarServiceAPI:
    build:
      context: ./carserviceapi
      dockerfile: Dockerfile
    image: carserviceapi:1
    restart: always
    hostname: CarServiceAPI
    ports:
      - 3001:3000
    networks:
      - netPRO390
    depends_on:
      - EurekaServer
      - CarServiceDB
      - CarManagerAPIGateway

  MaintenanceReminderServiceAPI:
    build:
      context: ./maintenancereminderserviceapi
      dockerfile: Dockerfile
    image: maintenancereminderserviceapi:1
    restart: always
    hostname: MaintenanceReminderServiceAPI
    ports:
      - 3002:3000
    networks:
      - netPRO390
    depends_on:
      - EurekaServer
      - CarManagerAPIGateway
      - CarServiceAPI
      - MaintenanceReminderServiceDB

#####################################################################################################

volumes:
  db_data_users:
  mongo_data:
  db_data_maintenancereminder:
  zookeeper-data:
  kafka-data:
  redis_data:




